[tool.pytest.ini_options]
addopts = "--strict-markers"
testpaths = "t/unit/"
python_classes = "test_*"
xfail_strict=true

[build-system]
requires = ['setuptools>=42']
build-backend = 'setuptools.build_meta'
